markdown: kramdown
exclude: ['README.md']

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Chase Whiteside
tagline:             'Design / Develop / Create'
description:         'My personal website where I share my work, thoughts and interests.'
url:                 http://cha.se.net
# baseurl:             '//chasebank.github.io/chase'
paginate:            5

# About/contact
author:
  name:              Chase Whiteside
  url:               https://cha.se.net
  email:             chase@cha.se.net

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]

collections:
  notes:
    output: true
    permalink: /:collection/:path/
    post_dirs: false
  portfolio: 
    output: true
    permalink: /portfolio/:path/
